
export const LOCATION_UPDATE = 'LOCATION_UPDATE';
export const PUT_DATA = 'PUT DATA';
export const PUT_NICKNAME = "PUT_NICKNAME";
export const REMOVE_DATA = 'REMOVE_DATA';
export const PUT_MI_DATA = 'PUT_MI_DATA';
export const REMOVE_SAVED_DATA = 'REMOVE_SAVED_DATA';
export const UPDATE_FOOTER = "UPDATE_FOOTER";
export const CONTACTOS_UPDATE = "CONTACTOS_UPDATE";

//SendBird Actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const DISCONNECT_SUCCESS = "DISCONNECT_SUCCESS";
export const INIT_MENU = "INIT_MENU";


export const OPEN_CHANNEL_LIST_SUCCESS = 'open_channel_list_success';
export const OPEN_CHANNEL_LIST_FAIL = 'open_channel_list_fail';

export const INIT_CHAT_SCREEN = 'INIT_CHAT_SCREEN';
export const CREATE_CHAT_HANDLER_SUCCESS = 'CREATE_CHAT_HANDLER_SUCCESS';
export const CREATE_CHAT_HANDLER_FAIL = 'CREATE_CHAT_HANDLER_FAIL';
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS';
export const MESSAGE_LIST_FAIL = 'MESSAGE_LIST_FAIL';
export const SEND_MESSAGE_TEMPORARY = 'SEND_MESSAGE_TEMPORARY';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
export const CHANNEL_EXIT_SUCCESS = 'CHANNEL_EXIT_SUCCESS';
export const CHANNEL_EXIT_FAIL = 'CHANNEL_EXIT_FAIL';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const MESSAGE_UPDATED = 'MESSAGE_UPDATED';
export const MESSAGE_DELETED = 'MESSAGE_DELETED';
